### ISSUE TITLE
Qty.parse('10 lb').kind() says 'mass', should be force.

### ISSUE THREAD

**Issue by sheam** [gentooboontoo/js-quantities#71]
For some reason Qty.parse('10 lb').kind() is reporting mass. Obviously the 10 is insignificant.

**Comment by gentooboontoo** [comment]
It seems there is a confusion between `lb` which is usually the unit of the pound as a mass and `lbf`, the unit of the pound as a force. So reporting mass for `lb` is correct here since it is its common use.

Of course, the meaning of the symbol of a unit could also be different depending on its domain of use. For the moment, the library does not support «contexts» but define units according to their most general meaning.

I am closing this issue but it could be eventually reopened to discuss about it in case I misunderstood it or if you have any further proposition.

**Comment by sheam** [comment]
Ok. In engineering a pound is a force, the corresponding mass is the slug. I have never heard of a pound-force before. Learn something new every day.

**Comment by sheam** [comment]
I should add that maybe non-candian engineering universities use different units.
